
const API_URL = "";
const preAccount = [{
        id: 'ex1',
        type: 'admin',
        nameLogin: 'admin',
        email: 'admin@SpeechGrammarList.com'
    },
    {
        id: 'ex1',
        type: 'user',
        nameLogin: 'user',
        email: 'admin@SpeechGrammarList.com'
    },
]
const preData = [{
        ID: "1",
        type: "Stupffed animal",
        name: "STRIPED BUFFALO SHIRT",
        img: "image/gauTrauAoKe1.jpg",
        img2: "image/gauTrauAoKe2.jpg",
        img3: "image/gauTrauAoKe3.jpg",
        price: 170000,
        price2: 250000,
        price3: 340000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Bong Ao Ke buffalo is currently sold at the store with 2 sizes 40cm, 50cm and 3 colors blue, pink,</br> orange, priced from only 190,000 VND",
        comment2: "Cotton Buffalo Plaid",
        comment3: "Close-up picture of Buffalo Bong Ao Ke head in blue"
    },
    {
        ID: "2",
        type: "Stupffed animal",
        name: "BUFFALO NECK PILLOWS",
        img: "image/gauCoTrau.jpg",
        img2: "image/gauCoTrau2.jpg",
        img3: "image/gauCoTrau3.jpg",
        price: 150000,
        price2: 200000,
        price3: 30000,
        size1: "1m2",
        size3: "1m5",
        size3: "1m",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Co Trau pillows are currently sold at stores with 3 colors: blue, red, and yellow, priced at only 150,000 VND",
        comment2: "Buffalo Neck Pillows - Red",
        comment: "Close-up picture of Red Buffalo Neck Pillow"
    },
    {
        ID: "3",
        type: "Stupffed animal",
        name: "Dinosaur teddy bear",
        img: "image/khungLong1.jpg",
        img2: "image/khungLong2.jpg",
        img3: "image/khungLong3.jpg",
        price: 390000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Fluffy Dinosaur Teddy Bear",
        comment2: "Cute pink dinosaur teddy bear",
        comment3: "Close-up picture of the Big Size's head"
    },
    {
        ID: "4",
        type: "Teddy",
        name: "TEDDY BEAR CREAM CAKE",
        img: "image/teddy.jpg",
        img2: "image/teddy4.jpg",
        img3: "image/teddy5.jpg",
        price: 490000,
        price2: 750000,
        price3: 985000,
        size1: "1m",
        size2: "1m3",
        size3: "1m6",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "5",
        type: "Teddy",
        name: "TEDDY ANGEL PINK",
        img: "image/teddyHong1.jpg",
        img2: "image/teddyHong2.jpg",
        img3: "image/teddyHong3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "1m6",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "12",
        type: "Teddy",
        name: "TEDDY ANGEL PINK",
        img: "image/td3_1.jpg",
        img2: "image/td3_2.jpg",
        img3: "image/td3_3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "1m6",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "12",
        type: "Teddy",
        name: "TEDDY",
        img: "image/td4-1.jpg",
        img2: "image/td4-2.jpg",
        img3: "image/td4-3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "1m6",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "6",
        type: "Cat",
        name: "cute cat",
        img: "image/meo2.jpg",
        img2: "image/meo4.jpg",
        img3: "image/meo5.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "8",
        type: "Cat",
        name: "cute cat",
        img: "image/smallCat1.jpg",
        img2: "image/smallCat2.jpg",
        img3: "image/smallCat3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "9",
        type: "Cat",
        name: "Black cat",
        img: "image/blackCat.jpg",
        img2: "image/blackCat2.jpg",
        img3: "image/blackCat3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "7",
        type: "Doremon",
        name: "Cute doremon",
        img: "image/doremon1.jpg",
        img2: "image/bigDoremon.jpg",
        img3: "image/bigDoremon1.jpg",
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "10",
        type: "Doremon",
        name: "Cute doremon",
        img: "image/doremondai1.jpg",
        img2: "image/doremondai2.jpg",
        img3: "image/doremondai3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },
    {
        ID: "11",
        type: "Doremon",
        name: "Cute doremon",
        img: "image/doremontt1.jpg",
        img2: "image/doremontt2.jpg",
        img3: "image/doremontt3.jpg",
        price: 290000,
        price2: 550000,
        price3: 585000,
        size1: "1m",
        size2: "1m3",
        size3: "50cm",
        status: "stocking",
        status2: "stocking",
        status3: "out of stock",
        comment: "Teddy heads & lovely kute tales are not you friends!",
        comment2: "Teddy heads & lovely kute tales are not you friends!",
        comment3: "Teddy heads & lovely kute tales are not you friends!"
    },


]
